### ISSUE TITLE
Mac issues.

### ISSUE THREAD

**Issue by squaresurf** [rkyleg/asdf-julia#2]
The first issue may not be anything at all. When I run `asdf list-all julia` I only get 0.6.1 as an output. Is that the only version of julia available?

The second issue is that `asdf install julia 0.6.1` does not install and results in the following:

```
$ asdf install julia 0.6.1
hdiutil: mount failed - image not recognized
cp: /Volumes/Julia-0.6.1//Julia-0.6.app/Contents/Resources/julia: No such file or directory
hdiutil: unmount: "/Volumes/Julia-0.6.1" failed to unmount due to error 2.
hdiutil: unmount failed - No such file or directory
```

I am currently running macOS Sierra version 10.12.6.

**Comment by sheeldotme** [comment]
I get the exact same error, also running Sierra with the same version.

**Comment by sheeldotme** [comment]
@squaresurf I've updated the package to work and submitted a PR: https://github.com/rkyleg/asdf-julia/pull/3, in the meantime feel free to install the plugin from my repo at: https://github.com/sheeldotme/asdf-julia

**Comment by sheeldotme** [comment]
@rkyleg I'm sure we can close this now that my PR has been merged.

**Comment by squaresurf** [comment]
I'm not in rush to install julia as I have a lot on my plate so I think I'll stay pointed at this plugin repo. I did just run `asdf plugin-update julia` and still only get a single version listed for `asdf list-all julia` and `asdf install julia 0.6.1` still fails. I'm not sure if the plugin needs to be released before I get the latest code from the merged PR.

**Comment by squaresurf** [comment]
Also, thank you very much @sheeldotme for your work!!! 🎉

**Comment by squaresurf** [comment]
This still appears to be broken:
```
$ asdf plugin-update julia
Updating julia...
Already up to date.
$ asdf install julia 0.6.2
hdiutil: mount failed - image not recognized
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
hdiutil: unmount: no file specified
Usage:	hdiutil unmount [options] <mountpoint>
	hdiutil unmount -help
```

**Comment by squaresurf** [comment]
I'm still on the same version of macOS, but will most likely update High Sierra over the weekend.
